services:
  nextcloud:
    container_name: nextcloud
    image: "${NEXTCLOUD_IMAGE}"
    depends_on:
      - postgres
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
      POSTGRES_HOST: postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - nextcloud-data:/var/www/html
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mariadb:
    container_name: mariadb
    image: mariadb:10.6.16
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_DATABASE: "${POSTGRES_USER}"
      MARIADB_USER: "${POSTGRES_USER}"
      MARIADB_PASSWORD: "${POSTGRES_PASSWORD}"
volumes:
  nextcloud-data:
  postgres-data:
